name: ğŸš€ğŸ”¥ Continuous Intergration Workflow
on:
  push:
    branches:
      - "**" # all branches

  pull_request:
    branches:
      - main

jobs:
  test:
    name: ğŸš€ğŸš€ Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
      - name: ğŸš€ Checkout Github Repository
        uses: actions/checkout@v4

      - name: ğŸš€ Setup Nodejs and NPM
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: ğŸš€ Installing Packages using Yarn
        run: yarn install

      - name: ğŸš€ Running Tests
        run: yarn test

  linting:
    name: ğŸš€ğŸš€ Code Linting
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
      - name: ğŸš€ Checkout Github Repository
        uses: actions/checkout@v4

      - name: ğŸš€ Setup Nodejs and NPM
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: ğŸš€ Installing Packages using Yarn
        run: yarn install

      - name: ğŸš€ Linting and building
        run: yarn lint && npx standard -v
