name: Publish Package (@crispengari/utils)
on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow}}-${{github.ref}}

jobs:
  build:
    name: Building the Package
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
      - name: Checkout Github Repository
        uses: actions/checkout@v4

      - name: Setup Nodejs and NPM
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org

      - name: Installing Packages using Yarn
        run: yarn install

      - name: Linting and building
        run: yarn lint && yarn build

      - name: Publish
        run: npm publish --access public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
